/* Control center: private metadata only; server text is always escaped. */
(() => {
  const e = escapeHTML;
  const size = n => !Number.isFinite(n) ? "Unknown size" : n < 1024 ? n + " B" : n < 1024**2 ? (n/1024).toFixed(1) + " KB" : n < 1024**3 ? (n/1024**2).toFixed(1) + " MB" : (n/1024**3).toFixed(1) + " GB";
  const when = value => value ? new Date(value * 1000).toLocaleString() : 'Not observed';
  const field = (id, label, value = '', type = 'text') => `<label>${e(label)}<input id="${id}" type="${type}" value="${e(value)}" autocomplete="off"></label>`;
  const options = values => values.map(([id,label]) => `<option value="${e(id)}">${e(label)}</option>`).join('');
  const safe = fn => async (...args) => { try { await fn(...args); } catch (err) { notice(err.message, true); if ($('center-dialog').open) $('center-dialog-error').textContent = err.message; } };
  let confirmAction = null;
  const modal = (title, html, label, action) => {
    $('center-dialog-title').textContent = title; $('center-dialog-body').innerHTML = html;
    $('center-dialog-error').textContent = ''; $('center-dialog-apply').textContent = label || 'Apply';
    $('center-dialog-apply').hidden = !action; confirmAction = action; $('center-dialog').showModal();
  };
  $('center-dialog-close').onclick = () => $('center-dialog').close();
  $('center-dialog-apply').onclick = safe(async () => {
    $('center-dialog-apply').disabled = true;
    try { await confirmAction(); } finally { $('center-dialog-apply').disabled = false; }
  });
  const done = result => { $('center-dialog').close(); if (result.job && window.trackOperation) window.trackOperation(result); else notice(result.note || 'Saved.'); };
  const table = (heads, rows) => `<div class="center-scroll"><table class="center-table"><thead><tr>${heads.map(h => `<th>${e(h)}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`;
  window.centerUI = {modal, safe, done, table, field, options, when, size};

  async function projects() {
    const value = await api('/api/workspace');
    $('sync-content').innerHTML = `<article class="panel"><div class="section-title"><h2>${value.enabled ? 'Following shared changes' : 'Automatic sync paused'}</h2><div class="button-row"><button id="sync-toggle">${value.enabled ? 'Pause automatic sync' : 'Enable automatic sync'}</button><button id="sync-now" class="primary">Synchronize now</button><button id="sync-refresh">Refresh status</button></div></div>${value.error ? `<p class="review-error">${e(value.error.message)}</p>` : ''}<p>${e(value.scope)}</p><p class="caption">Last checked: ${e(when(value.checked_at))}</p><p class="center-note">${e(value.runtime)}</p></article>${value.projects.length ? value.projects.map((p,i) => `<article class="panel center-card"><div class="section-title"><h2>${e(p.project.split(/[\\/]/).pop())}</h2><span class="pill">${e(p.status)}</span></div><p class="caption">${e(p.project)}</p>${window.projectMetadata ? window.projectMetadata(p) : ''}${p.template ? `<p>Template: ${e(p.template)}</p>` : ''}${p.detail ? `<p class="review-error">${e(p.detail)}</p>` : ''}<button data-follow="${i}" ${p.pinned ? 'disabled' : ''}>${p.paused ? 'Follow shared changes' : 'Pause this project'}</button>${p.pinned ? '<p class="caption">This project is pinned. Unpin deliberately with the constitution CLI before changing its installed baseline.</p>' : ''}</article>`).join('') : '<div class="center-empty"><h2>No enrolled projects yet.</h2><p>Apply a project template or onboard a repository with the constitution CLI. Local Control will show it here.</p></div>'}`;
    $('sync-toggle').onclick = safe(async () => { await api('/api/projects/follow', {enabled: !value.enabled}); await projects(); });
    $('sync-now').onclick = safe(async () => done(await api('/api/projects/sync', {})));
    $('sync-refresh').onclick = safe(projects);
    $('sync-content').querySelectorAll('[data-follow]').forEach(b => b.onclick = safe(async () => { const p = value.projects[+b.dataset.follow]; await api('/api/projects/follow', {project:p.project, paused:!p.paused}); await projects(); }));
  }

  function windowsHTML(observation) {
    return (observation.windows || []).map(w => `<div><div class="center-metadata"><strong>${e(w.bucket)} · ${e(w.window)}</strong><span>${w.duration_minutes == null ? 'Unknown window' : e(w.duration_minutes) + ' minute window'}</span></div><span class="center-kpi">${w.used_percent == null ? 'Unknown' : e(w.used_percent) + '% used'}</span>${w.used_percent == null ? '' : `<progress max="100" value="${Math.min(100,w.used_percent)}" aria-label="${e(w.bucket)} usage"></progress>`}<p class="caption">Resets ${e(when(w.resets_at))}</p></div>`).join('') || '<p class="caption">No provider limit windows available. This does not mean zero usage.</p>';
  }

  function machineHTML(id, name, report, observed) {
    const current = report?.observations?.codex || {};
    const codex = current.last_successful ? {...current.last_successful, status:'Last successful report · latest refresh failed'} : current;
    return `<article class="panel center-card"><span class="eyebrow">${e(name)} / CODEX</span><h2>${e(codex.plan || 'Account overview')}</h2><p class="center-login">${e(codex.login || 'Login not available')}</p><span class="pill">${e(codex.status || 'Not connected')}</span><p class="caption">${e(codex.source || (id === 'local' ? 'Enable the local CLI collector above, then refresh.' : 'Enable account sharing locally on this worker, then refresh.'))}<br>Observed ${e(when(codex.observed_at || observed))}</p>${windowsHTML(codex)}${codex.summary ? `<div class="center-metadata"><span>Lifetime tokens: ${e(codex.summary.lifetimeTokens ?? 'Unknown')}</span><span>Peak daily tokens: ${e(codex.summary.peakDailyTokens ?? 'Unknown')}</span></div>` : ''}${codex.daily?.length ? `<details><summary>Daily token activity · ${codex.daily.length} days</summary>${table(['Day','Tokens'],codex.daily.slice().reverse().map(v=>`<tr><td>${e(v.date)}</td><td>${e(v.tokens ?? 'Unknown')}</td></tr>`))}</details>` : ''}${codex.issues?.length ? `<p class="center-note">${codex.issues.map(v=>e(v.endpoint + ': ' + v.code)).join('<br>')}</p>` : ''}<div class="button-row"><button data-monitor-refresh="${e(id)}">Refresh usage</button><button data-machine-debug="${e(id)}">Diagnostics &amp; operation log</button></div></article>`;
  }

  async function accounts() {
    const value = await api('/api/monitoring'), local = value.local;
    $('accounts-content').innerHTML = `<article class="panel"><div class="section-title"><h2>Your control center</h2><div class="button-row"><button id="account-add" class="primary">+ Add subscription</button><button id="accounts-refresh">Refresh view</button></div></div><p>${e(local.note)}</p><label class="check"><input id="codex-monitor-enabled" type="checkbox" ${local.codex_enabled?'checked':''}> Read the local Codex CLI account every five minutes</label><p class="caption">Uses the CLI’s existing sign-in and documented read methods. Its login may differ from the desktop app. Workers opt in on their own machine. Cursor and other services use labelled manual/imported observations in this version; open the provider dashboard for authoritative billing.</p></article><div class="center-grid">${Object.entries(value.machines).map(([id,m])=>machineHTML(id,m.name,id==='local'?local:value.workers[id]?.report,value.workers[id]?.observed_at)).join('')}</div><div class="section-title"><h2>Subscriptions &amp; project assignments</h2></div><div class="center-grid">${Object.values(local.accounts).map(a=>`<article class="panel center-card"><span class="eyebrow">${e(a.provider)} / ${e(a.application || 'Application not set')}</span><h2>${e(a.label || a.plan || 'Subscription')}</h2><p class="center-login">${e(a.login || 'Login not entered')}</p><p>${e(a.plan)} · ${e(a.machine || 'Machine not assigned')}</p><p class="caption">${e(a.projects.join(' · ') || 'No project assignments')}</p>${a.usage?.length ? `<strong>${e(a.usage[0].used)} ${e(a.usage[0].unit)}${a.usage[0].limit == null ? '' : ' of '+e(a.usage[0].limit)}</strong><p class="caption">${e(a.usage[0].period)} · ${e(a.usage[0].source)}<br>Observed ${e(when(a.usage[0].observed_at))}</p>` : '<p class="caption">Usage unknown. Record an observation or import the portable usage format.</p>'}<div class="button-row"><button data-account-edit="${e(a.id)}">Edit</button><button data-usage="${e(a.id)}">Usage details</button><button data-account-log="${e(a.id)}">Integration log</button>${local.provider_links[a.provider]?`<a class="button" target="_blank" rel="noreferrer" href="${e(local.provider_links[a.provider])}">Provider dashboard ↗</a>`:''}</div></article>`).join('') || '<div class="center-empty">Add each subscription with its login, plan and machine. These records stay in private Local Control state.</div>'}</div><article class="panel"><h2>Collector log</h2>${table(['Observed','Integration','Status','Event'],local.events.slice(0,30).map(v=>`<tr><td>${e(when(v.time))}</td><td>${e(local.accounts[v.target]?.label || v.target)}</td><td>${e(v.status)}</td><td>${e(v.code.replaceAll('_',' '))}</td></tr>`))}</article>`;
    $('accounts-refresh').onclick = safe(accounts);
    $('codex-monitor-enabled').onchange = safe(async event => { await api('/api/monitoring/settings',{codex_enabled:event.target.checked}); if(event.target.checked) done(await api('/api/monitoring/refresh',{})); });
    function edit(account={}) {
      modal('Subscription details', `<p class="caption">Store login identifiers and labels only. Never enter passwords or API keys.</p><div class="studio-fields">${field('account-label','Label',account.label)}${field('account-login','Login email / identifier',account.login)}${field('account-plan','Plan',account.plan)}</div><div class="studio-fields"><label>Provider<select id="account-provider">${options(['openai','cursor','anthropic','xai','google','other'].map(v=>[v,v]))}</select></label>${field('account-app','Application',account.application)}${field('account-machine','Machine',account.machine)}</div><label>Projects · one per line<textarea id="account-projects" rows="3">${e((account.projects||[]).join('\n'))}</textarea></label>`, 'Save subscription', async()=>{
        await api('/api/monitoring/settings',{account:{id:account.id,provider:$('account-provider').value,label:$('account-label').value,login:$('account-login').value,plan:$('account-plan').value,machine:$('account-machine').value,application:$('account-app').value,projects:$('account-projects').value.split('\n').map(v=>v.trim()).filter(Boolean)}}); done({}); await accounts();
      }); $('account-provider').value = account.provider || 'openai';
    }
    $('account-add').onclick=()=>edit();
    $('accounts-content').querySelectorAll('[data-account-edit]').forEach(b=>b.onclick=()=>edit(local.accounts[b.dataset.accountEdit]));
    $('accounts-content').querySelectorAll('[data-monitor-refresh]').forEach(b=>b.onclick=safe(async()=>done(await api('/api/monitoring/refresh',{node:b.dataset.monitorRefresh}))));
    $('accounts-content').querySelectorAll('[data-machine-debug]').forEach(b=>b.onclick=safe(async()=>{
      const d=await api('/api/monitoring/diagnostics?node='+encodeURIComponent(b.dataset.machineDebug));
      modal('Machine diagnostics & operation log',`<p class="caption">Allowlisted support data. Credentials, paths, prompts and raw provider errors are excluded.</p><pre class="center-code">${e(JSON.stringify(d,null,2))}</pre>`,null,null);
    }));
    $('accounts-content').querySelectorAll('[data-account-log]').forEach(b=>b.onclick=()=>modal('Subscription integration log',table(['Observed','Status','Event'],local.events.filter(v=>v.target===b.dataset.accountLog).map(v=>`<tr><td>${e(when(v.time))}</td><td>${e(v.status)}</td><td>${e(v.code)}</td></tr>`)),null,null));
    $('accounts-content').querySelectorAll('[data-usage]').forEach(b=>b.onclick=()=>{
      const a=local.accounts[b.dataset.usage];
      modal('Usage observations', `<p class="caption">Observations retain their units and periods. They are not added across accounts or confused with live quota.</p>${table(['Observed','Period','Usage','Model','Source'],(a.usage||[]).map(v=>`<tr><td>${e(when(v.observed_at))}</td><td>${e(v.period)}</td><td>${e(v.used)} ${e(v.unit)}</td><td>${e(v.model)}</td><td>${e(v.source)}</td></tr>`))}<div class="studio-fields">${field('usage-used','Used','','number')}${field('usage-limit','Allowance (blank if unknown)','','number')}<label>Unit<select id="usage-unit">${options(['tokens','requests','USD','EUR','CHF','percent'].map(v=>[v,v]))}</select></label></div>${field('usage-period','Period / billing cycle')}${field('usage-model','Model (optional)')}<details><summary>Import a portable JSON observation</summary><p class="caption">Keys: used, limit, unit, period, observed_at (Unix seconds), model. Credential and arbitrary fields are discarded.</p><textarea id="usage-json" rows="4" class="code-editor" placeholder='{"used":1000,"unit":"tokens","period":"Current month"}'></textarea></details>`, 'Record observation', async()=>{
        const sample=$('usage-json').value.trim()?JSON.parse($('usage-json').value):{used:$('usage-used').value===''?null:Number($('usage-used').value),limit:$('usage-limit').value===''?null:Number($('usage-limit').value),unit:$('usage-unit').value,period:$('usage-period').value,model:$('usage-model').value};
        await api('/api/monitoring/usage',{id:a.id,sample});done({});await accounts();
      });
    });
  }

  async function storage() {
    const value=await api('/api/storage'), paths=value.paths;
    $('storage-content').innerHTML=`<article class="panel"><h2>Storage on this computer</h2><p>${e(value.note)}</p><form id="storage-form">${['models','studio','downloads'].map(k=>field('location-'+k,{models:'Ollama model weights',studio:'Private constitution library',downloads:'Managed downloads & worker packages'}[k],paths[k])+`<p class="caption">${e(size(value.volumes[k]?.free_bytes))} free on destination volume</p>`).join('')}<button class="primary">Preview location changes</button></form><p class="center-note">Observed model store: ${e(value.observed_models.path)}<br>${e(value.observed_models.evidence)}${value.pending_model_restart?'<br>Selected location differs from the observed store. Ollama may need a restart.':''}</p><button id="storage-apply-models">Apply Ollama location</button><p class="caption">This sets the OS environment on Windows/macOS. Restart Ollama when all its clients are idle. A running CPU fallback keeps its original store until restarted. Model weights are not moved automatically.</p><button id="storage-refresh">Refresh locations</button></article><article class="panel"><h2>Private configuration</h2><p class="caption">Controller: ${e(paths.configuration)}<br>Enrollment state: ${e(paths.constitution_state)}</p><p>For a new installation, use <code>--state-dir</code> or <code>AI_CONSTITUTION_LOCAL_HOME</code>. To relocate existing controller state, stop Local Control when sessions are idle, then preview a verified copy:</p><pre class="center-code">python scripts/local_control.py --state-dir ${e(JSON.stringify(paths.configuration))} relocate --destination "NEW_ABSOLUTE_DIRECTORY"</pre><p class="caption">Repeat with <code>--plan FINGERPRINT</code> from the preview, then start again. Originals remain and existing launch commands follow the relocation pointer. Project environment files have their own location under Configs &amp; backups.</p></article>`;
    $('storage-form').onsubmit=safe(async event=>{event.preventDefault();const selected=Object.fromEntries(['models','studio','downloads'].map(k=>[k,$('location-'+k).value])); const p=await api('/api/storage/preview',{paths:selected}); modal('Review storage changes',`<p>${e(p.note)}</p>${p.copies.map(c=>`<p>${e(c.source)} → ${e(c.destination)}<br>${e(c.files)} files · ${e(size(c.bytes))}</p>`).join('')}`,'Save locations',async()=>done(await api('/api/storage/save',{paths:selected,plan:p.plan})));});
    $('storage-apply-models').onclick=safe(async()=>done(await api('/api/storage/ollama',{})));
    $('storage-apply-models').insertAdjacentHTML('beforebegin','<button id="storage-copy-models">Copy existing model weights…</button> ');
    $('storage-copy-models').onclick=safe(async()=>{const p=await api('/api/storage/models-preview',{});modal('Copy existing model weights',`<p>${e(p.source)} → ${e(p.destination)}</p><p>${e(p.files)} files · ${e(size(p.bytes))}</p><p>Each file is verified. The original store remains. Choose a new destination directory; existing directories are never merged.</p>`,'Copy & verify',async()=>done(await api('/api/storage/models-copy',{plan:p.plan})));});
    $('storage-refresh').onclick=safe(storage);
  }

  async function workers() {
    const value=await api('/api/workers');
    $('workers-content').innerHTML=`<article class="panel"><div class="section-title"><h2>01 / Choose a package</h2><button id="worker-source">Prepare source package</button></div><p>${e(value.note)}</p><div class="center-grid">${value.packages.map(p=>`<article class="center-card"><span class="pill">${e(p.platform)} · ${e(p.architecture)}</span><h3>${p.kind==='source'?'Python source package':'Portable worker'}</h3><p class="caption">${e(p.signing)}<br>${(p.bytes/1024**2).toFixed(1)} MB</p><a class="button" href="${e(p.download)}" download>Download ZIP ↓</a><details><summary>SHA-256 checksum</summary><pre class="center-code">${e(p.sha256)}</pre></details></article>`).join('')||'<p>No packages cached yet. Prepare a source package for any supported OS, or register a reviewed portable build.</p>'}</div><p><a href="${e(value.builds_url)}" target="_blank" rel="noreferrer">Windows, macOS &amp; Linux preview builds ↗</a> <span class="caption">GitHub sign-in may be required for CI artifacts.</span></p><details><summary>Register a portable package on this controller</summary><pre class="center-code">python scripts/local_control.py packages add --file "PATH_TO_REVIEWED_WORKER.zip"</pre></details></article><article class="panel"><h2>02 / Start on the worker</h2><div class="studio-fields"><label>Operating system<select id="worker-os">${options([['windows','Windows'],['macos','macOS'],['linux','Linux']])}</select></label><label>Package type<select id="worker-kind">${options([['portable','Portable'],['source','Python source']])}</select></label></div><p>Extract the complete ZIP into a new folder on the worker. Open a terminal in that folder. Every command below works in a new terminal; no variables from earlier commands are needed.</p><div id="worker-commands"></div><p class="center-note">Upgrading: wait until model tasks are idle, stop the old worker, extract the new version into a separate folder and use the same state directory. Pairing and settings are retained. Do not overwrite a running executable or delete its private state.</p><p class="caption">Model weights are downloaded separately after pairing. Keep the worker on your private network. If a firewall prompt appears, allow only the private network and restrict access to your controller’s IP. Never expose port 8767 publicly.</p></article><article class="panel"><h2>03 / Pair it here</h2><p>Keep the worker running. Run the pairing command in another terminal on that computer, then paste its short-lived pairing record under Your machines → Add a machine.</p><button id="worker-pair" class="primary">Go to pairing →</button></article>`;
    const commands=()=>{
      const win=$('worker-os').value==='windows', source=$('worker-kind').value==='source';
      const exe=source?(win?'& .\\.venv\\Scripts\\python.exe scripts/local_control.py':'./.venv/bin/python scripts/local_control.py'):(win?"& '.\\app\\ai-constitution-local\\ai-constitution-local.exe'":'./app/ai-constitution-local/ai-constitution-local');
      const prefix=exe+(win?' --state-dir (Join-Path $env:USERPROFILE \'.config\\ai-constitution\\local-worker\')':' --state-dir "$HOME/.config/ai-constitution/local-worker"');
      const address=win?"(Read-Host 'Worker IPv4 address')":'WORKER_PRIVATE_IPV4';
      const steps=[];
      if(source)steps.push(['Prepare Python 3.11+ environment',win?'py -3 -m venv .venv\n& .\\.venv\\Scripts\\python.exe -m pip install -r requirements-local-node.txt':'python3 -m venv .venv\n./.venv/bin/python -m pip install -r requirements-local-node.txt']);
      steps.push(['Install model runtime and hardware helper (if needed)',prefix+' setup --ollama --llmfit']);
      steps.push(['Start worker · leave this terminal open',prefix+' node --address '+address]);
      steps.push(['Pairing · in another terminal',prefix+' pairing --address '+address]);
      steps.push(['Optional: share this OS user’s Codex login and usage',prefix+' monitor enable --share']);
      $('worker-commands').innerHTML=steps.map(([label,command],i)=>`<h3>${e(label)}</h3><pre class="center-code" id="worker-command-${i}">${e(command)}</pre><button data-copy-command="${i}">Copy command</button>`).join('');
      $('worker-commands').querySelectorAll('[data-copy-command]').forEach(b=>b.onclick=safe(async()=>{await navigator.clipboard.writeText($('worker-command-'+b.dataset.copyCommand).textContent);notice('Command copied.');}));
    }; $('worker-os').onchange=commands;$('worker-kind').onchange=commands;if(!value.packages.some(p=>p.kind==='portable'))$('worker-kind').value='source';commands();
    $('worker-source').onclick=safe(async()=>{await api('/api/workers/source',{});await workers();notice('Source package is ready to download.');});
    $('worker-pair').onclick=()=>page('machines');
  }

  async function vault() {
    const v=await api('/api/vault');
    $('vault-content').innerHTML=`<article class="panel"><p class="center-note">${e(v.note)}</p>${(v.warnings||[]).map(w=>`<p class="review-error">${e(w)}</p>`).join('')}<form id="vault-settings">${field('vault-root','Private project configuration root',v.config_root)}${field('vault-backups','Backup destination',v.backup_root)}<div class="studio-fields"><label class="check"><input type="checkbox" id="vault-scheduled" ${v.schedule.enabled?'checked':''}> Scheduled backups</label>${field('vault-hours','Every N hours',v.schedule.hours,'number')}</div><p class="caption">Last successful backup: ${e(when(v.last_success))}<br>Next due: ${e(when(v.next_due))}</p>${v.last_error?`<p class="review-error">${e(v.last_error)}</p>`:''}<button class="primary">Save locations &amp; schedule</button></form></article><article class="panel"><div class="section-title"><h2>Selected project folders</h2><div class="button-row"><button id="vault-add">+ Register project folder</button><button id="vault-backup" class="primary">Back up now</button><button id="vault-refresh">Refresh</button></div></div>${Object.keys(v.projects).length?table(['Project','Private folder','Checkout',''],Object.entries(v.projects).map(([id,p])=>`<tr><td>${e(p.name)}</td><td>${e(p.folder)}</td><td>${e(p.project||'Not linked')}</td><td><button data-vault-edit="${e(id)}">Edit mapping</button></td></tr>`)):'<p>No folders selected. Register the projects to include; other application settings stay outside these backups.</p>'}<details><summary>Existing folders under this root</summary>${v.available_folders.map(p=>`<p class="caption">${e(p.name)} · ${e(p.path)}</p>`).join('')||'<p>No folders found.</p>'}</details></article><article class="panel"><h2>Verified snapshots</h2>${v.snapshots.length?table(['Created','Projects','Files','Size',''],v.snapshots.map(s=>`<tr><td>${e(when(s.created))}</td><td>${e(s.projects.join(', '))}</td><td>${s.files}</td><td>${e(size(s.bytes))}</td><td><button data-restore="${e(s.id)}">Restore…</button></td></tr>`)):'<p>Your first completed backup will appear here.</p>'}</article>`;
    $('vault-settings').onsubmit=safe(async event=>{event.preventDefault();done(await api('/api/vault/settings',{config_root:$('vault-root').value,backup_root:$('vault-backups').value,schedule:{enabled:$('vault-scheduled').checked,hours:Number($('vault-hours').value)}}));await vault();});
    function edit(id='',p={}) {modal('Register a private project folder',`<p>Only this selected folder enters backups. Existing files are neither moved nor overwritten.</p><div class="studio-fields">${field('vault-id','Project ID',id)}${field('vault-name','Display name',p.name)}</div>${field('vault-folder','Existing private folder',p.folder||v.config_root)}${field('vault-project','Project checkout (optional)',p.project)}`,'Save mapping',async()=>{done(await api('/api/vault/settings',{entry:{id:$('vault-id').value,name:$('vault-name').value,folder:$('vault-folder').value,project:$('vault-project').value}}));await vault();});$('vault-id').readOnly=Boolean(id);}
    $('vault-add').onclick=()=>edit();$('vault-refresh').onclick=safe(vault);
    $('vault-content').querySelectorAll('[data-vault-edit]').forEach(b=>b.onclick=()=>edit(b.dataset.vaultEdit,v.projects[b.dataset.vaultEdit]));
    $('vault-backup').onclick=safe(async()=>{const p=await api('/api/vault/preview',{});modal('Review configuration backup',`<p>${p.files} files in ${p.projects.length} projects · ${e(size(p.bytes))}</p><p>Destination: ${e(p.destination)}</p><p class="center-note">The backup contains your selected configuration files, including secrets. It uses the local or encrypted backend selected below.</p>`,'Create verified backup',async()=>done(await api('/api/vault/backup',{plan:p.plan})));});
    $('vault-content').querySelectorAll('[data-restore]').forEach(b=>b.onclick=()=>{
      const snapshot=v.snapshots.find(s=>s.id===b.dataset.restore);
      modal('Restore into a new folder',`<label>Project<select id="restore-project">${options(snapshot.projects.map(p=>[p,p]))}</select></label>${field('restore-destination','New absolute directory')}<p>Existing environment files remain untouched. After reviewing the restored files, edit the project mapping when ready.</p>`,'Preview restore',async()=>{
        const data={snapshot:snapshot.id,project:$('restore-project').value,destination:$('restore-destination').value};
        const p=await api('/api/vault/restore-preview',data);modal('Review restoration',`<p>${e(p.note)}</p><p>${p.files} files · ${e(size(p.bytes))}<br>${e(p.destination)}</p>`,'Restore verified copy',async()=>done(await api('/api/vault/restore',{...data,plan:p.plan})));
      });
    });
  }

  $('template-capture').onclick=safe(async()=>{
    const vaultData=await api('/api/vault');
    modal('Create a template from an existing project',`${field('capture-project','Existing project directory')}${field('capture-id','New template identifier','captured-baseline')}${field('capture-name','Template name','Captured project baseline')}<label>Optional private config mapping · variable names only<select id="capture-config">${options([['','Do not inspect private configuration'],...Object.entries(vaultData.projects).map(([id,p])=>[id,p.name])])}</select></label><p class="caption">Inspects root manifests and apps, packages and services workspaces, plus environment-variable names. Does not execute project code or copy environment values, scripts, URLs or deployment files.</p>`,'Inspect project',async()=>{
      const result=await api('/api/studio/project-capture',{project:$('capture-project').value,id:$('capture-id').value,name:$('capture-name').value,configuration:$('capture-config').value});
      modal('Review detected architecture',`<p>${e(result.note)}</p>${table(['Manifest','Component','Declared version'],result.evidence.map(v=>`<tr><td>${e(v.file)}</td><td>${e(v.component)}</td><td>${e(v.version)}</td></tr>`))}<p>${result.environment_keys} environment-variable names found; values discarded.</p>${result.review.errors.map(v=>`<p class="review-error">${e(v)}</p>`).join('')}`,'Open in template editor',async()=>{$('center-dialog').close();window.useCapturedTemplate(result.template);notice('Proposed baseline opened. Review components, fill missing architecture details, then save.');});
    });
  });
  const pages={projects,accounts,storage,workers,vault};
  window.centerPage=safe(async name=>{if(pages[name])await pages[name]();});
  let polling=false;
  setInterval(async()=>{
    if(!authorized || polling || document.querySelector('dialog[open]'))return;
    const current=document.querySelector('.page.active')?.id;
    if(!['projects','accounts'].includes(current))return;
    polling=true;try{await window.centerPage(current);}finally{polling=false;}
  },30000);
})();
