/* Each entry is a real UI journey, with a documentation destination and caption. */
const {PROJECT, HOME} = require('../tests/fixtures/documentation.cjs');
const entries = [];
const add = (id, page, chapter, title, caption, steps = [], extra = {}) => entries.push({id, page, chapter, title, caption, steps, ...extra});
const click = selector => ['click', selector];
const fill = (selector, value) => ['fill', selector, value];
const select = (selector, value) => ['select', selector, value];
const chapters = {
  setup: ['Get started', 'getting-started.md'], overview: ['Overview and GPU release', 'local-control.md'],
  models: ['Choose and manage models', 'local-control.md'], machines: ['Machines and drivers', 'driver-maintenance.md'],
  connect: ['Connect Codex and Cursor projects', 'local-control.md'], architectures: ['Architecture templates', 'project-templates.md'],
  constitution: ['Constitution files', 'constitution-studio.md'], projects: ['Project onboarding and synchronization', 'control-center.md'],
  accounts: ['Applications and subscriptions', 'control-center.md'], workers: ['Worker installation and upgrades', 'windows-worker.md'],
  storage: ['Storage locations', 'control-center.md'], updates: ['Application and model updates', 'workspace-upgrades.md'],
  insights: ['Measured performance', 'workspace-upgrades.md'], vault: ['Private configuration and backups', 'encrypted-backups.md'],
  recovery: ['Progress and recovery', 'workspace-upgrades.md'], toolkit: ['Instruction toolkit and external setup', 'getting-started.md'],
};
const names = {setup: 'Get started', overview: 'Overview', models: 'Model library', machines: 'Your machines', connect: 'Connect a project', architectures: 'Project templates', constitution: 'Constitution files', projects: 'Projects', accounts: 'Apps & subscriptions', workers: 'Set up a worker', storage: 'Storage & locations', updates: 'Updates & model inbox', insights: 'Measured performance', vault: 'Configs & backups'};
for (const [page, title] of Object.entries(names)) add(page, page, page, title, 'Open ' + title + ' from the sidebar. The page below uses fictional documentation data.', [], {overview: true});
add('welcome', 'overview', 'setup', 'Open the authenticated dashboard', 'Opening the bare address shows this welcome dialog. Run the displayed open command to sign in locally.', [], {scenario: 'login', scope: '#login'});
add('gpu-gaming', 'overview', 'overview', 'Gaming mode', 'After draining active responses, subsequent requests use the tested fallback and managed GPU residency is checked. This state is simulated; no GPU benchmark is claimed.', [], {scenario: 'gaming'});
add('gpu-draining', 'overview', 'overview', 'Wait for the current response', 'A transition waits for the response already using the GPU. The next request can then use the fallback.', [], {scenario: 'draining'});
add('model-fit', 'models', 'models', 'Find models for your hardware', 'Choose Find models for my hardware. Estimated fit is shown separately from measured results.', [click('#suggest')], {scope: '#recommendations'});
add('hugging-face', 'models', 'models', 'Review GGUF files', 'Search Hugging Face, open the file list, then review the model card, license and download size. This repository and model are fictional.', [fill('#hf-query', 'demo-coder'), click('#hf-form button'), click('[data-files]')], {scope: '#models .panel:has(#hf-form)'});
add('model-route', 'models', 'models', 'Test a route', 'Use in project opens the route configuration. Choose primary or fallback and request CPU placement when appropriate.', [click('[data-use] >> nth=0')], {scope: '#configure-dialog'});
add('models-empty', 'models', 'models', 'No models installed', 'An empty inventory is a starting point, not an error. Install a runtime and choose a model before configuring routes.', [], {scenario: 'empty'});
add('driver-update', 'machines', 'machines', 'Prepare driver maintenance', 'Review the target computer and update method. Confirm other clients are idle before opening that machine’s native updater.', [click('[data-driver-update="local"]')], {scope: '#driver-dialog'});
add('machine-pairing', 'machines', 'machines', 'Pair a worker', 'Give the worker a recognizable name and paste its short-lived pairing record. The documentation leaves the credential field empty.', [fill('#pair-name', 'Work PC · demonstration')], {scope: '#pair-form'});
add('connect-launch', 'connect', 'connect', 'Open a local Codex session', 'Select the project directory and client. The launcher starts a new session; it does not migrate a running direct-provider session.', [fill('#launch-project', PROJECT), select('#launch-client', 'codex')], {scope: '#launch-form'});
add('cursor-task', 'connect', 'connect', 'Run Local Codex inside Cursor', 'The supported Cursor workflow is a generated workspace with Terminal → Run Task → AI Constitution: Local Codex.', [], {scope: '#connect .connect-grid'});
add('coding-evaluation', 'connect', 'connect', 'Compare bounded coding checks', 'Choose Compare results after evaluating configured routes. Values in this example are simulated fixture results.', [click('#show-evaluations')], {scope: '#connect .panel:has(#evaluation-results)'});
const baseline = [click('[data-template="0"]')];
add('template-editor', 'architectures', 'architectures', 'Customize a baseline', 'Choose Explore baseline to edit its components and decisions. The selected web baseline includes authentication, charts, email and SQL services.', baseline, {scope: '#template-workbench'});
add('template-component', 'architectures', 'architectures', 'Review a component', 'Each component records its repository, reviewed version, guidance and compatibility requirements.', [...baseline, click('[data-edit-component="0"]')], {scope: '#component-dialog'});
add('template-environment', 'architectures', 'architectures', 'Declare environment names', 'Scroll through component details to enter acceptance checks and environment-variable names and purposes. Credential values belong in the private configuration store.', [...baseline, click('[data-edit-component="0"]'), fill('#component-env', 'APP_ORIGIN | public | Application base URL'), ['inner-scroll', '#component-dialog', 'bottom']], {scope: '#component-dialog'});
add('template-revisions', 'architectures', 'architectures', 'Versions and inheritance', 'Open Versions & inheritance to inspect saved revisions or create a child of an immutable parent.', [...baseline, click('text=Versions & inheritance')], {scope: '#center-dialog'});
add('template-capture', 'architectures', 'architectures', 'Capture an existing project', 'Choose From existing project. Select the repository and, optionally, a private mapping to inspect variable names only.', [click('#template-capture'), fill('#capture-project', PROJECT), fill('#capture-id', 'orbit-baseline')], {scope: '#center-dialog'});
add('template-capture-review', 'architectures', 'architectures', 'Review detected architecture', 'Inspect project shows supported manifest evidence before opening the proposed baseline in the editor.', [click('#template-capture'), fill('#capture-project', PROJECT), click('#center-dialog-apply')], {scope: '#center-dialog'});
add('template-save', 'architectures', 'architectures', 'Review a baseline save', 'Saving first shows a managed-file preview. Review it before adding the baseline to your private library.', [...baseline, click('#template-save'), click('#studio-preview .diff-file summary')], {scope: '#studio-preview'});
add('template-apply', 'architectures', 'architectures', 'Apply a pinned revision', 'Enter the repository and project slug, select the revision policy, and preview generated files. Applying this plan does not install dependencies.', [...baseline, fill('#template-project', PROJECT), fill('#template-project-name', 'orbit-web'), select('#template-follow-policy', 'pinned'), click('#template-apply-preview'), click('#studio-preview .diff-file summary')], {scope: '#studio-preview'});
add('constitution-edit', 'constitution', 'constitution', 'Review instruction edits', 'Edit your private draft and choose Review & save draft. Validation and generated-file rebuilding happen before saving.', [fill('#library-editor', '# Shared working defaults\n\nPreserve existing work. Verify behavior before publishing.\n'), click('#library-save'), click('#studio-preview .diff-file summary')], {scope: '#studio-preview'});
add('constitution-generated', 'constitution', 'constitution', 'Inspect generated routing', 'Generated routing is view-only. Change source definitions and route choices, then rebuild.', [click('[data-file="routing.md"]')], {scope: '#constitution .file-workspace'});
add('constitution-activation', 'constitution', 'constitution', 'Review activation', 'Activation lists affected installations and file paths. Confirm instruction loading in a fresh client session afterward.', [click('#library-activate')], {scope: '#studio-preview'});
add('constitution-history', 'constitution', 'constitution', 'Recover a previous draft', 'Draft history retains reviewed saves. Later edits are protected when undoing a save.', [click('#library-history')], {scope: '#studio-preview'});
add('constitution-refresh', 'constitution', 'constitution', 'Review a library refresh', 'Bring unchanged draft files up to date while preserving customizations. Activation remains a separate reviewed step.', [click('#library-refresh'), click('#studio-preview .diff-file summary')], {scope: '#studio-preview'});
add('project-discovery', 'projects', 'projects', 'Choose repository roots', 'Bring my projects searches the roots you specify. It skips dependencies, build folders and filesystem links.', [click('#bring-projects'), fill('#discover-roots', HOME + '/projects')], {scope: '#center-dialog'});
const discovery = [click('#bring-projects'), fill('#discover-roots', HOME + '/projects'), click('#center-dialog-apply')];
add('project-selection', 'projects', 'projects', 'Select repositories and mappings', 'Choose repositories to enroll, associate existing private configuration, and explicitly adopt portable bundles when applicable.', discovery, {scope: '#center-dialog'});
add('project-preview', 'projects', 'projects', 'Review enrollment', 'The enrollment preview lists proposed managed-file changes. Only ready repositories are enrolled when you apply.', [...discovery, click('#center-dialog-apply')], {scope: '#center-dialog'});
add('project-conflict', 'projects', 'projects', 'Resolve a synchronization conflict', 'Local managed-file edits stop synchronization for the affected project. Review the change before retrying.', [], {scenario: 'conflict'});
add('projects-empty', 'projects', 'projects', 'Start with no enrolled projects', 'Use Bring my projects or apply a baseline to create your first enrollment.', [], {scenario: 'empty'});
add('subscription-edit', 'accounts', 'accounts', 'Identify a subscription', 'Record the login identifier, provider, application, plan and machine. These fields identify the account without storing its password.', [click('[data-account-edit] >> nth=0')], {scope: '#center-dialog'});
add('subscription-usage', 'accounts', 'accounts', 'Record a usage observation', 'Usage observations carry a unit, period, source and timestamp. They are separate from automatically collected quota windows.', [click('[data-usage] >> nth=0')], {scope: '#center-dialog'});
add('cost-connector', 'accounts', 'accounts', 'Configure read-only API costs', 'Select a supported organization connector and the name of an existing admin-key environment variable. Never paste the key itself.', [click('[data-connector-config] >> nth=0')], {scope: '#center-dialog'});
add('subscription-log', 'accounts', 'accounts', 'Inspect integration events', 'Integration logs show observation status and event codes for the selected subscription.', [click('[data-account-log] >> nth=0')], {scope: '#center-dialog'});
add('machine-diagnostics', 'accounts', 'accounts', 'Inspect worker diagnostics', 'Use Diagnostics & operation log for allowlisted support information. The example contains no credentials or conversation contents.', [click('[data-machine-debug] >> nth=0')], {scope: '#center-dialog'});
add('collector-failure', 'accounts', 'accounts', 'Retain the last successful report', 'A failed refresh is visible while the previous successful report remains available with its observation time.', [], {scenario: 'collector-failed'});
add('worker-download', 'workers', 'workers', 'Get a verified worker package', 'Choose Windows x64, Apple Silicon or Linux x64. Source packages support other compatible environments.', [click('#worker-release-download')], {scope: '#center-dialog'});
for (const os of ['windows', 'macos', 'linux']) add('worker-' + os, 'workers', 'workers', 'Worker commands · ' + os, 'Choose the OS and package type, then copy each command into a fresh terminal. These are screenshots of the dashboard’s instructions, not the operating-system terminal.', [select('#worker-os', os), ['scroll', '#worker-commands']], {scope: '#workers .panel:has(#worker-commands)'});
add('worker-maintenance', 'workers', 'workers', 'Worker version and updates', 'Review version and capabilities, check updates, manage login startup and prepare a guarded restart. Other controllers using the worker must also be idle.', [click('[data-worker-open]')], {scope: '#center-dialog'});
add('storage-preview', 'storage', 'storage', 'Review location changes', 'Choose new locations and review verified copies before saving. Existing storage is preserved.', [fill('#location-studio', HOME + '/new-private-library'), click('#storage-form button')], {scope: '#center-dialog'});
add('model-storage-copy', 'storage', 'storage', 'Copy and verify weights', 'Copy existing weights into a new destination. Review the file count and size before starting.', [click('#storage-copy-models')], {scope: '#center-dialog'});
add('update-release-notes', 'updates', 'updates', 'Read release changes', 'The header notification opens Updates. Expand Release changes before choosing a verified download. The displayed release is fictional.', [click('#updates-content details >> nth=0')]);
add('update-restart', 'updates', 'updates', 'Review an update restart', 'After verification, restart only when tracked and external clients are idle. Private settings and model storage are retained.', [click('#update-apply')], {scenario: 'staged', scope: '#center-dialog'});
add('update-blocked', 'updates', 'updates', 'Active work blocks restart', 'Active responses and managed sessions block restart. Finish the work and request a fresh preview.', [click('#update-apply')], {scenario: 'blocked', scope: '#center-dialog'});
add('update-rollback', 'updates', 'updates', 'Review application rollback', 'Rollback uses the retained application and the same idle-service safeguards.', [click('#update-rollback')], {scope: '#center-dialog'});
add('model-inbox-detail', 'updates', 'updates', 'Inspect changed model fields', 'Review catalog differences and routing impact. Importing definitions does not establish account access or change a running model.', [click('#model-diff-list summary')], {scope: '#updates-content .panel >> nth=1'});
add('model-inbox-apply', 'updates', 'updates', 'Review catalog application', 'Apply only the reviewed definitions. A transaction snapshot is retained and stale previews are refused.', [click('#model-apply')], {scope: '#center-dialog'});
add('performance-empty', 'insights', 'insights', 'No measured profiles yet', 'Configure and evaluate a model before using measured profiles. Estimates and observations remain separate.', [], {scenario: 'empty'});
add('config-mapping', 'vault', 'vault', 'Register a project configuration folder', 'Map an existing private configuration folder to its project. Only selected folders enter backups.', [click('[data-vault-edit]')], {scope: '#center-dialog'});
add('backup-preview', 'vault', 'vault', 'Review a configuration backup', 'Check selected projects, file count, size and the actual backend destination before creating a verified backup.', [click('#vault-backup')], {scope: '#center-dialog'});
add('backup-encryption', 'vault', 'vault', 'Configure encrypted backups', 'Configure the restic repository, password-file location or environment-variable name, and retention count. The password itself is never entered here.', [click('#restic-settings')], {scope: '#center-dialog'});
add('backup-initialize', 'vault', 'vault', 'Initialize the repository', 'Initialize the configured encrypted repository and retain its password separately before backing up.', [click('#restic-init')], {scope: '#center-dialog'});
add('backup-schedule', 'vault', 'vault', 'Schedule backups outside the dashboard', 'Create a task for the current OS user. Its credential source must be available to the scheduled process.', [click('#backup-os-schedule')], {scope: '#center-dialog'});
add('backup-retention', 'vault', 'vault', 'Review retention deletion', 'Deletion is limited to the reviewed snapshot IDs in this controller’s tag group.', [click('#restic-retention')], {scope: '#center-dialog'});
add('backup-restore', 'vault', 'vault', 'Select an encrypted snapshot', 'Choose a snapshot and a new directory before requesting the restoration preview.', [click('#restic-restore'), fill('#encrypted-destination', HOME + '/restore-drill/orbit-web')], {scope: '#center-dialog'});
add('backup-restore-preview', 'vault', 'vault', 'Review an encrypted restore', 'Restore and verify into the new private destination. Active configuration is preserved.', [click('#restic-restore'), fill('#encrypted-destination', HOME + '/restore-drill/orbit-web'), click('#center-dialog-apply')], {scope: '#center-dialog'});
add('local-restore-preview', 'vault', 'vault', 'Restore a local snapshot', 'Local snapshots also restore into a new directory. Review restored files before changing the project mapping.', [click('[data-restore]'), fill('#restore-destination', HOME + '/restore-drill/local-copy'), click('#center-dialog-apply')], {scope: '#center-dialog'});
add('notifications', 'overview', 'recovery', 'Review actionable failures', 'Unacknowledged failures remain visible. Open the recovery page for a fresh preview and retry.', [click('#notifications-button')], {scenario: 'failure', scope: '#center-dialog'});
add('operation-progress', 'models', 'recovery', 'Keep using the dashboard during a job', 'A model download shows durable operation progress. This demonstration simulates progress without downloading weights.', [fill('#pull-model', 'demo-coder:7b'), click('#pull-form button')]);
add('support-report', 'overview', 'recovery', 'Preview support information', 'Review the allowlisted diagnostic report before downloading it. Prompts, credentials and private raw provider errors are excluded.', [click('#support-export')], {scope: '#overview .service-panel'});
add('mobile-updates', 'updates', 'recovery', 'Use a smaller screen', 'The same update controls remain available on a smaller viewport. This is responsive-browser coverage, not a native mobile app.', [], {viewport: {width: 390, height: 844}, fullPage: true});
add('tablet-projects', 'projects', 'recovery', 'Project cards on a tablet-sized viewport', 'Project information and actions adapt to the available width.', [], {viewport: {width: 820, height: 1180}, fullPage: true});
add('toolkit-check', null, 'toolkit', 'Verify the instruction toolkit', 'A rendered transcript of a real isolated CLI check. This image is not a screenshot of a terminal application.', [], {transcript: 'check'});
add('toolkit-install-preview', null, 'toolkit', 'Preview installation', 'A rendered summary from a real dry-run against a temporary home. No live Codex or Cursor files are written.', [], {transcript: 'install'});
module.exports = {entries, chapters, names};
